# Use an official Python runtime as a parent image
FROM python:3.6

# Set the working directory to /app
WORKDIR /app/

# Make port 80 available to the world outside this container
EXPOSE 80

# Copy the current directory contents into the container at /app
ADD . /app/

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt


# AWS credentials
ENV AWS_ACCESS_KEY_ID=XXXXXXXX
ENV AWS_SECRET_ACCESS_KEY=XXXXXXX
ENV AWS_DEFAULT_REGION=XXXXXXX


# QUEUES
ENV Q_WRITER=XXXXXXXX


# REDIS
ENV REDIS_HOST=XXXXXXXX
ENV REDIS_PORT=XXXX
ENV REDIS_DB=XXXXXX

# Run app.py when the container launches
ENTRYPOINT ["python", "WikiBot.py"]